version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: twilio
    versions:
    - 6.51.1
    - 6.52.0
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: coveralls
    versions:
    - 3.0.0
  - dependency-name: gunicorn
    versions:
    - 20.0.4
