language: python
python:
    - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database sendit;' -U postgres

install:
  - pip install pipenv
  - pipenv install

script:
  - pytest  --cov --disable-warnings

sudo: required

after_success: 
- coveralls
